
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './test-helper.mjs';
import {handle} from './api.mjs';
test('032: token roles, independent state, persistence, feedback, reset and revocation',async()=>{
 const f=await fixture(),origin='https://human-test.invalid';
 const call=async(cookie,path,body,originHeader=origin)=>handle(f.env,new Request(origin+'/api/v3/'+path,{method:body?'POST':'GET',headers:{cookie:cookie||'',origin:originHeader,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}));
 const login=async i=>{const r=await call('','login',{token:f.tokens[i]});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];};
 const a=await login(0),b=await login(1),jan=await login(10),admin=await login(11);
 const state=async cookie=>(await (await call(cookie,'state')).json()).state;
 assert.equal((await call('','state')).status,401);
 assert.equal((await call('','login',{token:'0'.repeat(64)})).status,403);
 assert.equal((await call('','login',{token:f.tokens[0]},'https://evil.invalid')).status,403);
 let revision=0;const save=async event=>{const r=await call(a,'event',{baseRevision:revision,event});assert.equal(r.status,200);revision=(await r.json()).revision;};
 await save({type:'focus',id:'a-focus',data:{title:'A privat fokus',why:'Fiktivt',notice:'Mer utrymme'}});
 await save({type:'action',id:'a-action',data:{what:'Fråga först',situation:'Fiktivt möte',when:'Nu'}});
 await save({type:'outcome',id:'a-action',data:{result:'Ja',happened:'Lyssnade',evidence:'Fiktiv observation',next:'Igen'}});
 assert.equal((await state(b)).focus.length,0);
 assert.equal((await state(await login(0))).focus[0].title,'A privat fokus');
 assert.equal((await call(b,'state?participant=test01')).status,404);
 assert.equal((await call(b,'history?participant=test01')).status,404);
 assert.equal((await call(b,'recommend?participant=test01',{baseRevision:0,title:'Utan filter'})).status,404);
 assert.equal((await call(b,'manage')).status,403);
 assert.equal((await call(b,'event',{baseRevision:0,event:{type:'recommend'}})).status,400);
 const config=await (await call(b,'config')).json();assert.equal(config.people.length,1);assert.equal(config.person.role,'participant');
 assert.equal((await call(a,'login',{bootstrap:f.tokens[0],person:'jan'})).status,403);
 assert.equal((await call(a,'../test-identity')).status,404);
 assert.equal((await call(jan,'history?participant=test01')).status,403);
 assert.equal((await call(admin,'manage')).status,403);
 assert.deepEqual((await (await call(jan,'state?participant=test01')).json()).state.shared,[]);
 await save({type:'share',target:'focus:a-focus',enabled:true});
 assert.equal((await (await call(jan,'state?participant=test01')).json()).state.shared.length,1);
 const adminState=JSON.stringify(await (await call(admin,'state?participant=test01')).json());assert.ok(!adminState.includes('A privat fokus'));
 await save({type:'share',target:'focus:a-focus',enabled:false});
 assert.deepEqual((await (await call(jan,'state?participant=test01')).json()).state.shared,[]);
 const feedback=['Tydligt','Fiktiv osäkerhet','Samtalet','','Mer tid'];
 assert.equal((await call(a,'feedback',{answers:feedback})).status,200);
 assert.deepEqual(await (await call(b,'feedback')).json(),['','','','','']);
 assert.deepEqual((await (await call(jan,'manage')).json())[0].feedback,feedback);
 assert.ok(!JSON.stringify(await state(a)).includes('Fiktiv osäkerhet'));
 assert.equal((await call(a,'event',{baseRevision:0,event:{type:'clock',day:21}})).status,409);
 await call(jan,'manage',{id:'test01',action:'reset'});
 assert.equal((await call(a,'state')).status,401);
 assert.equal((await state(await login(0))).focus.length,0);
 assert.deepEqual(await (await call(await login(0),'feedback')).json(),['','','','','']);
 await call(jan,'manage',{id:'test02',action:'revoke'});
 assert.equal((await call(b,'state')).status,401);
 assert.equal((await call('','login',{token:f.tokens[1]})).status,403);
 await call(jan,'manage',{id:'test01',action:'delete'});
 assert.equal((await call('','login',{token:f.tokens[0]})).status,403);
 for(const table of ['ht032_state','ht032_history','ht032_feedback','ht032_session'])assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM '+table+' WHERE user_id=?').get('test01').n,0);
 const raw=f.sqlite.prepare('SELECT * FROM ht032_session').all();for(const t of f.tokens)assert.ok(!JSON.stringify(raw).includes(t));
 f.sqlite.close();
});
